#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    Quit,
    HardQuit,
    NavigateUp,
    NavigateDown,
    NavigateLeft,
    NavigateRight,
    Select,
    AddProject,
    AddWorktree,
    AddSession,
    SplitPaneVertical,
    SplitPaneHorizontal,
    AddRoutine,
    Delete,
    Edit,
    EditGlobalConfig,
    SetAlias,
    Refresh,
    Help,
    ConfirmYes,
    NextAttention,
    PrevAttention,
    DismissAttention,
    NextActive,
    PrevActive,
    NextIdle,
    PrevIdle,
    NextSession,
    PrevSession,
    SendCtrlC,
    AssignGroup,
    EnterMove,
    JumpProjectDown,
    JumpProjectUp,
    SearchStart,
    GroupPrev,
    GroupNext,
    GroupManager,
    InputChar(char),
    InputBackspace,
    InputTab,
    InputBackTab,
    InputEscape,
    LiteralEscape,
    TerminalKey(crossterm::event::KeyEvent),
    TerminalKeys(Vec<crossterm::event::KeyEvent>),
    TerminalPaste(String),
    TerminalPrefixedPaste(crossterm::event::KeyEvent, String),
    TerminalMouse(crossterm::event::MouseEvent),
    TerminalPrefixedMouse(crossterm::event::KeyEvent, crossterm::event::MouseEvent),
    ToggleTerminalSidebar,
    MouseClick { col: u16, row: u16 },
    MouseScroll { col: u16, row: u16, delta: i8 },
    Resize,
    None,
}
