#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    Quit,
    NavigateUp,
    NavigateDown,
    NavigateLeft,
    NavigateRight,
    Select,
    AddProject,
    AddWorktree,
    AddSession,
    OpenRun,
    Delete,
    Clean,
    Edit,
    SetAlias,
    Refresh,
    Help,
    ConfirmYes,
    NextAttention,
    EnterMove,
    InputChar(char),
    InputBackspace,
    InputTab,
    InputEscape,
    None,
}
